name: CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm run type-check
            - run: npm run lint
            - run: npm test -- --coverage